### PR TITLE
fix: Task comments are not working - EXO-66946 - Meeds-io/meeds#1242

### PR DESCRIPTION
**Pull request by akhanfir**
Prior to this change, when you open the task comments drawer and close it or click the back arrow and then open the task comments drawer again, task comments cannot be added. To solve this problem, when closing this drawer, it falsely overwrites the dom drawer using v-if and takes it as conditions attribute the state of the drawer, that's why it has to add an attribute of the drawer which changes with the change of the drawer. After this change, the rich editor works correctly and is reset the second time the drawer is opened.

### CODE REVIEW

**Comment by srenault-meeds** [comment]
Hello
is this one related to this issue: https://github.com/Meeds-io/meeds/issues/1184?

If so, then, we have a (little) problem. Someone from the community has already proposed a fix.
Thanks for your confirmation

**Comment by srenault-meeds** [comment]
cc @rdenarie @plamarque

**Comment by rdenarie** [comment]
Thanks @srenault-meeds for the notification
@akhanfir @Jihed525 can you check if it is the same ?
If yes, I think we should keep the community proposition as it  is more advanced

**Comment by akhanfir** [comment]
Thanks for the suggestion @srenault-meeds @rdenarie 
This helped me to diagnose more the original problem, but, the proposed fix will not be sufficient and even worse, it will cause a side effet.
In fact, the proposed fix does not solve the problem and it invokes another bug:
1. When commenting on the task we notice that the task comments editor is not closed.
2. When adding a new comment without clicking submit and closing the drawer and reopening it, we see that the content of the comment retains the same text that we wrote before closing the drawer.
Due to these side effects, I suggest not considering the proposed fix.

**Comment by srenault-meeds** [comment]
ok thanks for this feedback @akhanfir 
I let you decide what is better then
And depending on your decision, I will inform the contribution from the community member
cc @boubaker FYI

**Comment by Jihed525** [comment]
wdyt @rdenarie @boubaker ? should we keep @akhanfir fix as he explained the side effects of community user's fix proposition ?

**Comment by rdenarie** [comment]
For me, we should keep the @akhanfir fix, and close the community proposition fix.

**Comment by boubaker** [comment]
> For me, we should keep the @akhanfir fix, and close the community proposition fix.

No objection for me, I let you choose what is better.

We should just consider one of both issues and close the other as duplicated:
* https://github.com/Meeds-io/meeds/issues/1242
* https://github.com/Meeds-io/meeds/issues/1184

**Comment by Jihed525** [comment]
We keep this one then
is it approved @rdenarie ?

**Review by rdenarie — CHANGES_REQUESTED** [review]
Can you update the commit message ? 
Currently, it is the complete description of the problem.

Can you follow the dev guidelines about commit messages ?

Thanks

**Comment by Jihed525** [comment]
is it ok now @rdenarie ?

**Review by rdenarie — APPROVED** [review]

**Pull request merged**
