### PR TITLE
TASK-XXXXX: Fix liquibase initialization for postgres

### PR DESCRIPTION
**Pull request by hbenali**

### CODE REVIEW

**Review by rdenarie — COMMENTED** [review]
Does theses modifications will work on platform which have already applied the changelog ?

**Comment by rdenarie** [comment]
Can you give some informations about theses changes ? 
Why it is needed ? 
Do we need to change it on existing table (tribe for example) ?
Are all db engines concerned ?

**Comment by rdenarie** [comment]
Can you give some informations about theses changes ? 
Why it is needed ? 
Do we need to change it on existing table (tribe for example) ?
Are all db engines concerned ?

**Review by rdenarie — COMMENTED** [review]
Can you give some informations about theses changes ? 
Why it is needed ? 
Do we need to change it on existing table (tribe for example) ?
Are all db engines concerned ?

**Comment by hbenali** [comment]
> Can you give some informations about theses changes ? Why it is needed ? Do we need to change it on existing table (tribe for example)? Are all db engines concerned ?

The aim of the PR is not to modify the structures of the tables of the existing databases. The problem occurs during database initialization. The `BIT` type is no longer supported for the recently upgraded version of Liquibase with Postgresql. I am adding valid checksums to avoid existing database issues and to ignore these changesets.

**Comment by rdenarie** [comment]
finally, no need to fix ?

**Pull request closed without merging**
